export enum CATEGORIES {
    SNAP_DECISIONS = 'snap_decisions',
    FASHION = 'fashion',
    FUNNY = 'funny',
    SPORTS = 'sports',
    WHAT_IS_BETTER = 'what_is_better',
    JUST_CURIOUS = 'just_curious',
    IN_THE_NEWS = 'in_the_news',
    BEST_PHOTO = 'best_photo',
    MEDIA = 'media',
    TRAVEL = 'travel',
    BEAUTY = 'beauty',
    FOOD = 'food',
    CARS = 'cars',
}